url: "https://ramidem.github.io/"
baseurl: ""
author: "Med Aduh"
tagline: "A self-taught Software Developer from the Philippines."
twitter: "ramidem"

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
