title: Med Aduh
description: Self-taught web developer from the Philippines
baseurl:  ""
url: ""

twitter: ramidem
github: ramidem

permalink: /:title
#exclude:  _drafts
markdown: kramdown

include: .well_known
